### ISSUE TITLE
Breaks on some worlds

### ISSUE THREAD

**Issue by Oreolek** [jonajames/mc2mt#1]
```
Traceback (most recent call last):
  File "mc2mt.py", line 106, in <module>
    for found_section in mcaIterator(args.input+"/region/",mca_filenames[i]):
  File "mc2mt.py", line 30, in mcaIterator
    for section in chunk.value[''].value['Level'].value['Sections'].value:
KeyError: 'Sections'
```

**Comment by jonajames** [comment]
If there's no sections is probably because the chunk is just empty.
I updated the code to make it ignore the error.

Can you confirm it's working now?
If not can you provide a non-working map?

**Comment by Oreolek** [comment]
Thanks, much better now.
